### ISSUE TITLE
ソースファイルの分割

### ISSUE THREAD

**Issue by takahashim** [ttrace/vscode-language-japanese-novel#13]
ユニットテストなどの自動化テストを導入できると不具合を避けやすくなると思っているのですが、そのためには関数やクラスがexportできる必要があるようです。

VS Code Extensionの場合、extension.tsから各機能を別ファイルに抽出し、それらに対してテストを書くのが一般的なようです。他のextensionのコードを参考にした限りでは、extension.tsには最低限 `activate()` と `deactivate()` だけというケースもあるようですが、そこまでしないにしてももう少しシンプルにしても良さそうです。

* 設定関連
* local server関連
* PDF出力（vivliostyle）関連
* HTML生成関連

あたりを切り出すのを考えていますが、どうでしょうか？

**Comment by ttrace** [comment]
ありがとうございます。
複数のワークスペースを開いているときの処理を追加したいので、websocketsをlocalserverからさらに独立させたいとは思っていました。
ホストしている時と、ホストしているhttpにテキストを投げるときの二種類が必要になりそうです。

**Comment by ttrace** [comment]
分割、お願いしてもよろしいでしょうか。

**Comment by takahashim** [comment]
「複数のワークスペース」は難しそうですね…！　確かにlocal serverとWebSocket周りを整理しないと大変そうです。

それはさておき、まずは設定関連の分離からPRを送ってみます。

**Comment by ttrace** [comment]
進み始めたので、イシューをクローズします。
