### ISSUE TITLE
Cannot read property 'fsPath' of undefined

### ISSUE THREAD

**Issue by kagurazakarasen** [ttrace/vscode-language-japanese-novel#28]
Ver1.0.1 で縦書き表示ができなくなってしまいました。
ランタイムの状態を表示させると、表題のようなエラーが出ていてアクティブにできていないようです。

一度アンインストールして、再度インストールしてみても同様のエラーでした。

![2021-09-26_23h44_30](https://user-images.githubusercontent.com/26425768/134812832-39d28fda-086d-43b8-8a54-4157ff05983a.png)

**Comment by ttrace** [comment]
申し訳ありません。再現できません。どのバージョンまで戻ると動きますか？

**Comment by ttrace** [comment]
1.0.2で、fsPathがundefinedになりそうな場所を手当てしてみました。
お手数おかけしますが、お確かめください。

**Comment by kagurazakarasen** [comment]
ありがとうございます。確認したところ
1.0.2で、また違うエラーになりました。
![2021-09-27_12h35_48](https://user-images.githubusercontent.com/26425768/134842196-a8bb46f0-20a6-4ebe-a080-59e790837644.png)

過去のバージョンにさかのぼると、0.6.0まで戻れば縦書き表示できましたが、0.7.0では
![2021-09-27_12h42_14](https://user-images.githubusercontent.com/26425768/134842354-305d1561-49b0-4e99-bdd7-1844390e3354.png)
縦書きプレビュー時にこのようなエラーがポップアップしてきます。

**Comment by kagurazakarasen** [comment]
バージョンを細かく変えながら調査してみました。
0.6.1　ー＞ OK
0.6.2　ー＞エラー
エラー内容は0.7.0と同じモノのようです
![image](https://user-images.githubusercontent.com/26425768/134842796-767a0e28-42c1-47c5-8897-e6d193f85bf0.png)

**Comment by ttrace** [comment]
0.6.2で変更した部分は、ほぼまるっきり残っていないので今動かない原因とは変わってしまっている気がします。
VS Codeのバージョンはどのあたりですか？

**Comment by kagurazakarasen** [comment]
VS Codeのバージョン情報張ります
![image](https://user-images.githubusercontent.com/26425768/134891276-518d58dd-4961-4730-9273-5ac2a6262e78.png)

この状態で、1.0.2にアップデートしたところ、やはり縦書きは正常に動作せず、
![image](https://user-images.githubusercontent.com/26425768/134891421-b017713a-536c-432f-8d93-723cc034213d.png)

このエラー表示になってしまっています。

**Comment by kagurazakarasen** [comment]
すみません、今まではデスクトップPC（Win10）で行っていましたが、同じくWin10のノートPCでVer1.0.2で縦書き表示を行ってみたところ、正常に動作しました。
ですので、どうやらデスクトップPC側の特定環境の問題のようです。

念のため、動作したノートPC側のVS Codeのバージョン表示を貼ります。

![2021-09-27_19h36_36](https://user-images.githubusercontent.com/26425768/134895319-34d890e0-8748-4169-9439-bd5c39bb41b7.png)

バージョンは同じで、system setup か user setup の違いぐらいしかなさそうです。。

デスクトップPC側でいろいろ入れてある拡張等を抜いて、ノートの環境に合わせて再確認してみることにします。

**Comment by kagurazakarasen** [comment]
度々すみません。デスクトップPCのほうですが、ノートPCと同じ拡張状態にしても症状かわらず、
novel writer以外のすべてのエクステンションを停止させ、再起動しても Ver 1.0.2 は

![image](https://user-images.githubusercontent.com/26425768/134901320-bcd0ef06-c6f3-466d-bb43-2d1a29706ef9.png)

このエラーのままになっています。
他になにか原因想定できますでしょうか？

**Comment by ttrace** [comment]
ひょっとすると、文章やフォルダ名に引っかかっているかもしれません。
空のフォルダーや、他のプロジェクトを開いても発生しますでしょうか。

**Comment by kagurazakarasen** [comment]
D:\work\novel_test\test.txt で発生。（縦書きビューは真っ黒（ページ端のグラデは見えます）
その後、
D:\work\empty という空のフォルダを作成し、その上でやってみましたが同様です。

ただ、マシン自体リブートして、最初にVS Codeを立ち上げ、開いた瞬間には、縦書き表示は真っ黒で見得ませんが、ランタイムの状態を見てもなにも表示されていない（エラー表示がない）状態が起りました。

その後、いったん「縦書きプレビュー枠」を閉じて再度「縦書きプレビュー」を実行すると、
![2021-09-28_19h44_21](https://user-images.githubusercontent.com/26425768/135073289-f1791f34-851b-40d6-b31b-8478969a3f80.png)
このようなエラー表示になりました。（ポート？　アドレスがもう使われている？）

↑までのテストはワークスペースを開かずフォルダを開いて行っていましたが、ワークスペース （デフォルトの workspace.code-workspace )を保存してワークスペースを開いても同様の状態です。

**Comment by ttrace** [comment]
初回起動時の原稿用紙的なグリッドは描かれていますか？
一行だけ画面の右端の外側に送られてしまう（見えなくなってしまう）バグが時折発生します。
ひょっとするとそのせいで初回起動時の動作がわからなくなってしまっている、ということはないでしょうか。
二度目の起動に失敗した時の 8080番と5001番が使われていることで警告が出るのは既知のものです。

**Comment by kagurazakarasen** [comment]
あ、グリッド表示はでていません。黒いグラデーションのみです。
![2021-09-29_11h35_13](https://user-images.githubusercontent.com/26425768/135193538-456fe75c-cfb4-4095-91e1-aa3307713ab5.png)
このような表示になります＞縦書きプレビュー

**Comment by ttrace** [comment]
なるほど。
本文を作るところで落ちているようですね。エラーに出ている正規表現が関係しているかもしれません。
novel-writerのsettingsの、ユーザー正規表現には何が登録されいますか？

**Comment by kagurazakarasen** [comment]
原因わかりました。これでした！

`   "Novel.preview.userregex": 
        ["([0-9]{2,})","<span class=\"tcy\">$1</span>"]`

となっていました。
おそらく縦中横を入れようとして失敗していたようです。[ ～ ]内を削除してみたところ、無事表示されるようになりました。

これで大丈夫とおもいます。
お手数をおかけしました。ありがとうございます。

**Comment by ttrace** [comment]
なるほど！
では以下の正規表現を試してみてください。

`["(?!<[0-9])([0-9][0-9])(?![0-9])","<span class=\"tcy\">$1</span>"]`

**Comment by kagurazakarasen** [comment]
ありがとうございます。コピペしていれてみましたが、また真っ黒グラデのみのビューになり、
Invalid regular expression: /(/: Unterminated group
のエラーが再発してしまいました＞＜

**Comment by ttrace** [comment]
同じ正規表現は、ノートPCでエラーになりますか？

**Comment by kagurazakarasen** [comment]
はい、ノートでも同様に真っ黒グラデのみとなって
Invalid regular expression: /(/: Unterminated group
がでてしまいます。

**Comment by ttrace** [comment]
なんででしょう……
下でもダメでしょうか。
`["/(?!<[0-9])([0-9][0-9])(?![0-9])/","<span class=\"tcy\">$1</span>"]`

**Comment by kagurazakarasen** [comment]
ありがとうございます。が、やはりだめでした。
ノート、デスクトップともに正規表現いれると縦書きが消えてエラーになりますー＞＜

**Comment by ttrace** [comment]
まずは二桁の数字の自動縦中横を本体機能に組み込みますね。

**Comment by ttrace** [comment]
ありがとうございます。一旦クローズします。
(が含まれる時の正規表現は、別イシューを立てます。
