### ISSUE TITLE
形態素解析を利用したカーソル移動について

### ISSUE THREAD

**Issue by higumachan** [ttrace/vscode-language-japanese-novel#34]
はじめまして、[この記事](https://logmi.jp/tech/articles/325715)を読んでもの書きではないですが、自分が今作っているライブラリ(のラッパ)と親和性が高そうなのでIssueを建てました。

現在私は[lindera-js](https://github.com/higumachan/lindera-js)というブラウザで動作する、形態素解析のライブラリを作っています。
もしよろしければ、このpluginに試験的に組み込んで見たいと思っているのですがよろしいでしょうか？

よろしいならば、私はあまりVSCodeのプラグインの構造については詳しくないので、どのへんにコードを入れてみたほうが良いのかを知っている範囲で問題ないので教えていただけると助かります。

**Comment by ttrace** [comment]
お知らせりがとうございます！
Issueは読んでいましたが、私もどのように実装すればいいのか迷っていましたが、すでにキーマップなどが完成している別のプラグインをフォークして実装してしまいました。
期待に応えられず申し訳ありません。

**Comment by ttrace** [comment]
形態素解析によるカーソル移動を行うプラグインのレポジトリです。
参考になれば幸いです。
https://github.com/ttrace/japanese-morhpeme-handler
