### ISSUE TITLE
Characters at the beginning of each line are hidden

### ISSUE THREAD

**Issue by prokosna** [ttrace/vscode-language-japanese-novel#40]
2e59fc0825af62addb3bb9d38e30609997b82db1 にて、行の先頭の文字が隠れてしまうようです。(Windows, Linux)

![novel-writer-issue](https://user-images.githubusercontent.com/16056246/166498417-410c102e-66e3-465d-a9c8-824c98c7ff4e.png)

> Version: 1.66.2 (system setup)
> Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
> Date: 2022-04-11T07:46:01.075Z
> Electron: 17.2.0
> Chromium: 98.0.4758.109
> Node.js: 16.13.0
> V8: 9.8.177.11-electron.0
> OS: Windows_NT x64 10.0.19043

とりあえず私の方で修正した PR は出しますが、もし再現性がなければ close してください。

**Comment by ttrace** [comment]
報告ありがとうございます。
現在、Tokenizeブランチで利用しているポート番号の表示などを予定していまして、その余波が出てしまったようです。
直しておきます。

**Comment by ttrace** [comment]
おそらく、1.2以降で治っているかと思います。一度クローズします。
