### ISSUE TITLE
品詞ハイライトが機能していない

### ISSUE THREAD

**Issue by chickweed1232** [ttrace/vscode-language-japanese-novel#66]
大変便利な拡張機能をありがとうございます。  
小説を書く際にありがたく使わせていただいてます。

# 発生している不具合

品詞ハイライトが全く機能していません。

# 試したこと

・言語を変更する  
　→日本語・英語共に効果なし

・設定ファイルを全て削除して再インストールする  
　→効果なし

・付録のハイライト設定をsetting.jsonに記述する  
　→効果なし

・配色テーマを変更する  
　→効果なし

・コマンドパレットから、Novel:品詞ハイライト停止を実行する  
　→command 'Novel.hide-morpheme' not foundというエラーが発生する

関連性があるかわかりませんが、キャッチできないエラーが検出されました　Cannot read properties of undefined (reading 'conjugated_type')というメッセージも表示されています。

**Comment by haedoyeon** [comment]
本文のファイルが*.txtになっていますか？私の場合、.txtをつけずにファイルを作ってやったら同様にハイライトが機能しませんでしたが、txtにしたらすぐできました。

**Comment by chickweed1232** [comment]
追記
ファイルの拡張子はtxtで保存されており、言語モードもnovelになっています。

**Comment by kaito-yoshitate** [comment]
@chickweed1232  
私もWindows11環境で品詞ハイライトが機能していませんでしたが、 #67 マージ後に機能するようになりました。  
もし、Windows環境をお使いでしたら挙動に変化はないでしょうか？

**Comment by ttrace** [comment]
報告ありがとうございます。
もしも挙動に変化がありましたら教えてください。

品詞ハイライトについては安定しているとは言い難いので、監視を続けます。

**Comment by ttrace** [comment]
1.7.8で「Novel.品詞ハイライト停止を実行する」コマンドは削除しました。

**Comment by ttrace** [comment]
1.8.2で、文章の末尾がサ変接続する名詞の時に、品詞ハイライトが停止していたバグに対処しました。 @chickweed1232 さんから報告いただいた、以下のエラーは出なくなっているかと思います。
ご確認ください。

> 関連性があるかわかりませんが、キャッチできないエラーが検出されました　Cannot read properties of undefined (reading 'conjugated_type')というメッセージも表示されています。

**Comment by ttrace** [comment]
ご確認ありがとうございます。では、クローズします。
