### ISSUE TITLE
原稿テキストファイルと一般テキストファイルの区別する拡張子

### ISSUE THREAD

**Issue by ekawatani** [ttrace/vscode-language-japanese-novel#73]
原稿テキストファイルと一般テキストファイルの区別がつきません。以前に投稿された #70 を見ましたが、小説と全く関係ないプロジェクトを開いた場合でも「原稿」や「Draft」といったフォルダを作る必要があるので、解決策になっていません。

`*.txt`, `*.md`など既存の拡張子だと競合するので、好きな拡張子または`*.novel`などを指定出来るようにできませんか？

**Comment by ttrace** [comment]
申し訳ないのですが、オリジナルの拡張子は開発者がメンテナンスできないため、実装しません。
お手数をおかけしますが、novel-writerの起動が邪魔であれば、Profile機能でnovel-writerが有効な環境を切り分けることをお勧めします（私はそうやっています）。

**Comment by ttrace** [comment]
issueをクローズします

**Comment by ttrace** [comment]
issueをクローズします
