### ISSUE TITLE
ワークスペース内にReactプロジェクトを作成したらマークダウンの動作が遅くなる

### ISSUE THREAD

**Issue by Beikon215** [ttrace/vscode-language-japanese-novel#74]
Create React Appを使用してReactプロジェクトを作成した後、同じワークスペース内のマークダウンファイルの改行やプレビュー表示が非常に遅くなりました。

この現象はnovel-writer拡張機能を有効化した際に発生したため、おそらくこの拡張機能が原因ではないかと考えています。

原稿ファイルの拡張子を.txtに設定し、ファイルの言語モードをマークダウンに設定した際にも同様の問題が発生しました。

過去に同様の報告している方もおり、Reactプロジェクトを作る過程で編集される文字量が多いために発生している可能性があります。
[関連報告](https://zenn.dev/dmnt/articles/3061e949451d1f)

**Comment by ttrace** [comment]
ご報告ありがとうございます。取得するファイルがあまりに多い時は、カウンターそのものも動作しないようにしたいと思います。

**Comment by ttrace** [comment]
原稿（あるいはDraft）に入っている時だけ動作するように変更したほうが良さそうですね。issueを残しておきます。
また現在、文字数を数える関数はところどころに同期関数が残っているため、非同期化してタイピングに影響させないように変更していきます。

**Comment by ttrace** [comment]
3.0.2 にて、Draft(あるいは原稿)フォルダーの中にないテキストファイルでは編集距離を計算しないように変更しました。
ソフトウエア開発で使われる長いテキストファイルで反応が極めて悪くなる現象は発生しにくくなったかと思います。
