### ISSUE TITLE
ソースコード中の変数名をcamelCaseに変更したい

### ISSUE THREAD

**Issue by takahashim** [ttrace/vscode-language-japanese-novel#8]
実は私のVS Codeでソースコードのextension.tsを開くと、以下のように変数名のところに軒並み指摘の波線が入るのでした。

<img width="666" alt="vscode-variables" src="https://user-images.githubusercontent.com/10401/118859562-55cecc80-b915-11eb-8da0-e27d456a2eee.png">

これはVS Codeに「Code Spell Checker」という拡張を入れており、「mypath」等を知らない単語だと認識しているためのようです。

さすがにちょっと煩わしいので何とかならないかと調べてみたところ、この警告は変数名をいわゆるcamelCaseにすると概ね解消されるようでした。
「TypeScript Deep Dive」の非公式スタイルガイドでもTypeScriptの変数名はcamelCaseが推奨のようなので、変更してみるのはいかがでしょうか？
https://typescript-jp.gitbook.io/deep-dive/styleguide

**Comment by ttrace** [comment]
こちら了解です。camelCaseに変更します。
なぜか全て小文字のほうがいいと思い込んでいました。

**Comment by takahashim** [comment]
ありがとうございます、こちら #10 でお送りしました。

**Comment by ttrace** [comment]
ありがとうございます。
読みやすくもありますね、マージします。
