### ISSUE TITLE
V0.7.4で縦書きプレビューできず

### ISSUE THREAD

**Issue by kagurazakarasen** [ttrace/vscode-language-japanese-novel#9]
V0.7.3までは正常にプレビューできていましたが、0.7.4でプレビューできなくなりました。
ログ（メイン）には
[2021-05-20 23:20:06.041] [main] [error] CodeWindow: failed to load workbench window: ERR_BLOCKED_BY_CSP
とでてきています。（0.7.4時）
0.7.3へダウングレードすると正常にプレビューできます。

それと、おそらく0.7.4時点からVSCodeのマーケットプレースに
![image](https://user-images.githubusercontent.com/26425768/118995781-5f623e00-b9c2-11eb-8ba0-07121b4ec74c.png)
このようなコメント表記がでてきてしまっています。

**Comment by ttrace** [comment]
失礼しました。0.7.5では動作するかと思います。

**Comment by kagurazakarasen** [comment]
ありがとうございます。v0.7.6 で無事縦書きプレビューでるようになりました。
（マーケットプレースの説明文も治っています）

**Comment by ttrace** [comment]
報告ありがとうございます！
